Make search
illiapelypenko/homefind pull request #2
Opened 2020-09-03 20:55 UTC by illiapelypenko

Add search page

2020-09-07 06:45 UTC, uladzislau-stuk commented
Remove 'Розклад_кафедра' from the project

2020-09-07 08:28 UTC, uladzislau-stuk requested changes

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/App/App.jsx
> +  };
Remove it please or try not to include such changes to pull request

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/App/App.jsx
> +              />
I guess it would be better to create 'navigation' folder folder and move all things related to one there, navigation/index.jsx

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/App/App.jsx
> +  };
You don't need it here, please move to SearchPage, I think you can move data via router params

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/Header/Header.jsx
>            <span>Homefind</span>
I don't think it's a good naming for classes, you started using BEM at your previous project, so you can keep here

home-logo
home-logo_icon

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/Header/Header.jsx
>            <span>Your faves</span>
header_button
header_button-icon

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/LocationButton.jsx
> +export default LocationButton;
I don't think we need to create component for svg, rework it please

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +  timeout;
User private instance property syntax: #timeout

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +      };
We can move it to componentDidUpdate

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +  }
-> handleChange

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +      }));
I might have confused you when I have said that it's better to use callback in this.setState, it's better to use when your next value in the state depends on previous one
https://reactjs.org/docs/faq-state.html#why-is-setstate-giving-me-the-wrong-value

Here you can use this.setState({//...})

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +
Order of imports:

// modules
// components
// assetss
// utils
// styles

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +    this.setState(() => ({ inputValue: '' }));
Here you can use this.setState({//...})

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +    this.setState(() => ({ inputValue }), updateSuggestions);
Here you can use this.setState({//...})

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +    }));
Here you can use this.setState({//...})

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +  };
Here you can use this.setState({//...})

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +      <main className={styles.searchPage}>
searchPage -> container

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +              }))
move to method

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +            }}
move to method

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +            className={styles.locationInput}
location-input

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +              }
move to methods

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +                : null}
```
              {displaySuggestions && suggestions.map((suggestion, index) => (
                   <li
                        key={index}
                        className={styles.suggestion}
                        onClick={() => this.handleSuggestionClick(suggestion)}
                      >
                        {suggestion.state_code}, {suggestion.city}
                      </li>
                ))}
```

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +              {displayError ? <li className={styles.error}>{error}</li> : null}
`
 {displayError && <li className={styles.location-input_error}>{error}</li>}
`

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +        <div className={styles.background}>
background -> page-content

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +          <input type='submit' value='Go' className={styles.submitBtn} />
form_submit-button

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.module.scss
> +    flex: 0 1;
Bt default flex-grow: 0 and flex-shrink: 1, so you can skip it

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +              className={`${styles.placeholder} ${
location-input_placeholder

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.jsx
> +                inputValue && styles.placeholderOnTop
location-input_placeholder__top

2020-09-07 08:28 UTC, uladzislau-stuk commented on src/components/SearchPage/SearchPage.module.scss
> +  background: #e6605b;
Move colors to consts

2020-09-10 08:20 UTC, uladzislau-stuk requested changes

2020-09-10 08:20 UTC, uladzislau-stuk commented on .vscode/launch.json
> +  // Use IntelliSense to learn about possible attributes.
Add this file to gitignore please

2020-09-10 08:20 UTC, uladzislau-stuk commented on src/components/Search/Search.jsx
> +  getSuggestions = async place => {
You need to declare methods after lifecycles ones

2020-09-10 08:20 UTC, uladzislau-stuk commented on src/components/Search/Search.jsx
> +      const text = `${suggestion.state_code}, ${suggestion.city}`;
move to separate method `${suggestion.state_code}, ${suggestion.city}`

2020-09-10 08:20 UTC, uladzislau-stuk commented on src/components/Search/Search.jsx
> +    function hightlight(suggestion) {
current function should b placed outside render method

2020-09-10 08:20 UTC, uladzislau-stuk commented on src/components/Search/Search.jsx
> +    }
Need to discuss

2020-09-10 08:20 UTC, uladzislau-stuk commented on src/components/Search/Search.jsx
> +            }`}
Just interesting, try inputValue && styles.placeholderTop

2020-09-10 08:20 UTC, uladzislau-stuk commented on src/components/Search/Search.jsx
> +              !error &&
Write in one line please

2020-09-10 14:52 UTC, illiapelypenko commented on src/components/Search/Search.jsx
> +      const text = `${suggestion.state_code}, ${suggestion.city}`;
I used it just twice. I guess creating function for this case is unnecessary

2020-09-10 14:58 UTC, illiapelypenko commented on src/components/Search/Search.jsx
> +              !error &&
I tried, but my auto-formatting code tool (which uses best code practices) insists on this writing style

2020-09-15 09:17 UTC, uladzislau-stuk requested changes

2020-09-15 09:17 UTC, uladzislau-stuk commented on src/components/Search/Search.jsx
> +            </svg>
Did you forget import as ReactComponent?

2020-09-15 09:17 UTC, uladzislau-stuk commented on src/components/Search/Search.jsx
> +            {error && <li className={styles.error}>{error}</li>}
I would rather not clutter layout and create separate method:  
`
renderCitySuggestions = (items) => (
   .items(suggestion => suggestion.area_type === 'city')
                .map((suggestion, index) => (
                  <li
                    onClick={() => this.handleSuggestionClick(suggestion)}
                    key={index}
                    className={styles.suggestion}
                  >
                    {suggestion.state_code}, {suggestion.city}
                  </li>
                ))
                .slice(0, 6)
)
`

2020-09-15 12:49 UTC, uladzislau-stuk approved these changes

2020-09-15 12:49 UTC, merged